name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: "253704407ae68efa37bf8f5b59b3e06dd40d3d3f"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "unix-x64"
          buildPreset: "unix"
